# Generated by Django 6.0.6 on 2026-06-11 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text_1', models.TextField()),
                ('text_2', models.TextField(blank=True)),
                ('text_3', models.TextField(blank=True)),
                ('text_4', models.TextField(blank=True)),
                ('text_5', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VideoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='RenderJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_video', models.FileField(blank=True, null=True, upload_to='renders/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rendering', 'Rendering'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting_template.content')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setting_template.videotemplate'),
        ),
    ]
