# Generated by Django 6.0.6 on 2026-06-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting_template', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videotemplate',
            options={'verbose_name': 'Video Template', 'verbose_name_plural': 'Video Templates'},
        ),
        migrations.AlterModelTable(
            name='videotemplate',
            table='VideoTemplate',
        ),
    ]
